### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by matzero** [sikanhe/reason-graphql#12]
I've clone it compile it, run the tests, now how do I run the server?

**Comment by sikanhe** [comment]
Hey @matzero I am creating an example repository soon with a server example. Stay tuned. The TLDR is that you have to parse the post request into `query` string and `variables` and pass it to the schema.

**Comment by sikanhe** [comment]
@matzero Just released a (experimental) middleware package for `bs-express`. You can check out the usage here: https://github.com/sikanhe/reason-graphql/blob/master/reason-graphql-bs-express/examples/server.re 

If you want to run it on your own server implementation you can peek into the package to see how I parsed the request body to feed it to the graphql server execution function.

To make it work you would want to install `reason-graphql` and `reason-graphql-bs-express` at latest versions.

**Comment by matzero** [comment]
@sikanhe this is great! Let me take a gander later on this week and I will report back.

**Comment by sikanhe** [comment]
We have a more full example now at https://github.com/sikanhe/reason-graphql/tree/master/examples/starwars-api
