### ISSUE TITLE
Using with Apollo server?  Gradual migration path? 

### ISSUE THREAD

**Issue by vonwao** [sikanhe/reason-graphql#25]
What's the way to implement this in a real-world app?  Is it ready to use in a real server?

**Comment by sikanhe** [comment]
@vonwao This is not meant to be used w/ Apollo Server or GraphQLJS. It's an implementation from scratch. If you happen to use typescript, checkout https://github.com/sikanhe/gqtx if you want a similar experience but use with `graphql-js` or Apollo Server
