### ISSUE TITLE
Attribution?

### ISSUE THREAD

**Issue by anmonteiro** [sikanhe/reason-graphql#30]
Reading through the code, it seems like this library is almost a direct port of https://github.com/andreas/ocaml-graphql-server to Reason, but I didn't find the original library's copyright notice or license anywhere in the repo.

Am I missing something?

**Comment by sikanhe** [comment]
It's in the first paragraph of readme. The repo is also MIT just like the original OCaml repo.

**Comment by anmonteiro** [comment]
> but I didn't find the original library's copyright notice or license anywhere in the repo.

I'm not trying to be difficult but saying that the library is inspired by the other is not abiding by the terms of the license. Having been bitten by this once before, I'm just trying to help here.

**Comment by sikanhe** [comment]
@anmonteiro I will change the wording, thanks for looking out.

**Comment by sikanhe** [comment]
@anmonteiro done!
