### ISSUE TITLE
Suggestion: remove 'variations'

### ISSUE THREAD

**Issue by leeor** [sikanhe/reason-graphql#36]
#### Motivation

Reduce the dependency footprint. Right now, due to https://github.com/RationalJS/future/issues/53, I cannot update my bs-platform version to 8.

Since these variations are very simple and short, they could be documented instead of being a part of the source code. There's also the option of making each variation a separate npm module, but it might be overkill.

I'll be happy to submit a PR if you agree with this suggestion.

**Comment by sikanhe** [comment]
@leeor Seems good with me. Happy to accept PR. 

1 Suggestion i have to is to prefer reason-promise over Future library - Future library does not handle event loop starvation properly

**Comment by leeor** [comment]
PR merged, thanks @sikanhe.

**Comment by leeor** [comment]
Actually, #37 was closed without merging, so I'm reopening this.

**Comment by sikanhe** [comment]
In master - need to add back readme/guide - will open up a new issue for that
