### ISSUE TITLE
Change `list` GraphQL type to accept an `array`

### ISSUE THREAD

**Issue by fakenickels** [sikanhe/reason-graphql#38]
As we are in a JS env it would make more sense. Opening this issue as a suggestion and for the discussion!

**Comment by leeor** [comment]
I was about to suggest this too once I'm done with the current PR I'm working on.

**Comment by sikanhe** [comment]
good point

**Comment by sikanhe** [comment]
Implemented in https://github.com/sikanhe/reason-graphql/pull/41
